#!/usr/bin/env python3
"""SAVEONSUB build step: catalog.json -> assets/catalog.js (+ derived fields).
Run locally: python3 build_catalog.py"""
import json, math

cat = json.load(open('catalog.json'))
rate = cat['meta']['usd_anchor_rate']

for p in cat['products']:
    cheapest = min(p['plans'], key=lambda x: x['bdt'])
    official_bdt = round(p['official_usd'] * rate)
    p['from_bdt'] = cheapest['bdt']
    p['from_tos'] = cheapest['tos']
    p['official_bdt'] = official_bdt
    p['save_pct'] = max(0, round(100 - (cheapest['bdt'] / official_bdt * 100))) if official_bdt > cheapest['bdt'] else 0
    # Ensure faq exists for JS consumers that read p.faq[0]
    if 'faq' not in p or not isinstance(p.get('faq'), list):
        p['faq'] = [{"q":f"What is {p['name']}?", "a":f"{p['name']} at honest BD prices via bKash/Nagad."}]
    # Ensure bundles field exists for JS
    if 'bundles' not in p:
        p['bundles'] = []
    # Ensure save_bdt exists for bundles section
    if 'save_bdt' not in p:
        p['save_bdt'] = 0

out = "/* GENERATED by build_catalog.py — edit catalog.json, not this file */\nconst CATALOG = " + json.dumps(cat, ensure_ascii=False, separators=(',', ':')) + ";\n"
open('assets/catalog.js', 'w').write(out)
print(f"OK: {len(cat['products'])} products -> assets/catalog.js ({len(out)} bytes)")
