#!/usr/bin/env python3
"""Generate internal D1 seed SQL for the v3 shadow commerce runtime.

All current plans seed as `unknown` with NULL price. This script never promotes a
plan to sellable and never copies catalog prices into D1. It creates only stable
plan/product identity + source provenance so later approved authority records can
be applied separately.
"""
from __future__ import annotations

import pathlib

from catalog_model import load_catalog

ROOT = pathlib.Path(__file__).resolve().parent
OUT = ROOT / "commerce-worker" / "generated" / "plan_runtime_seed.sql"


def sql_text(value: object) -> str:
    return "'" + str(value or "").replace("'", "''") + "'"


def build_sql() -> str:
    catalog = load_catalog()
    source_sha = catalog.get("meta", {}).get("v3_model", {}).get("source_sha256", "")
    lines = [
        "-- GENERATED by seed_plan_runtime.py; internal shadow seed only.",
        "-- No approved price or commercial authorization is asserted here.",
        "BEGIN TRANSACTION;",
    ]
    count = 0
    for product in catalog.get("products", []):
        for plan in product.get("plans", []):
            count += 1
            plan_id = plan["plan_id_v3"]
            product_id = product["id"]
            lines += [
                "INSERT INTO plan_runtime(",
                "  plan_id, product_id, commercial_state, price_bdt, currency, authority_ref, source_sha256, updated_at",
                ") VALUES (",
                f"  {sql_text(plan_id)}, {sql_text(product_id)}, 'unknown', NULL, 'BDT', NULL, {sql_text(source_sha)}, CURRENT_TIMESTAMP",
                ") ON CONFLICT(plan_id) DO UPDATE SET",
                "  product_id = excluded.product_id,",
                "  source_sha256 = excluded.source_sha256,",
                "  updated_at = CURRENT_TIMESTAMP",
                "WHERE plan_runtime.commercial_state = 'unknown' AND plan_runtime.price_bdt IS NULL;",
            ]
    lines += [
        "COMMIT;",
        f"-- plan_runtime rows represented: {count}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    sql = build_sql()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(sql, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    print("seed posture: commercial_state=unknown, price_bdt=NULL")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
